[package]
name = "sample-fns"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
jni = "0.21"
serde_json = "1"
bench-runner = { path = "../bench-runner" }
